version: "3.4"
services:
  nginx:
    image: nginx
    networks:
      - webgateway
    deploy:
      placement:
        constraints:
          - node.role == worker
      labels:
        traefik.frontend.rule: "Host:myapp.!!.com"
        traefik.port: "80"
      replicas: 1
      restart_policy:
        condition: on-failure

networks:
  webgateway:
    external: true
