version: "3.2"
services:
  traefik:
    image: traefik
    command:
      - --web
      - --docker
      - --docker.swarmmode
      - --docker.domain=docker.localhost
      - --docker.watch=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - webgateway
    ports:
      - target: 80
        published: 80
      - 8080:8080
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure

networks:
  webgateway:
    driver: overlay
    external: true
